spring.application.name=UserService

server.port=9091
spring.datasource.url=jdbc:mysql://localhost:3306/micro_app
spring.datasource.username=root
spring.datasource.password=Krsna@108
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true
